apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: aero-scheduler
    plugins:
      multiPoint:
        enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
extenders:
  - urlPrefix: "http://aero-scheduler-extender.aero.svc.cluster.local:8080"
    filterVerb: "filter"
    scoreVerb: "score"
    preemptVerb: "preempt"
    weight: 10
    nodeCacheCapable: false
    enableHTTPS: false
    ignorable: false
